
# Input folder with SAR data (zip format)
# input_folder: /media/nas_data/Thomas/Sentinel_1_data/biebrza_poland
# input_folder: /media/nas_data/Thomas/Sentinel_1_data/foggia_italy
# input_folder: /media/nas_data/Thomas/S1/data/Wallerfing_MNI
input_folder: /media/tweiss/Daten/try_preprocessing/data

# Folder to store the pre-processed data
# output_folder: /media/nas_data/Thomas/S1/processed/MNI_2017_new_final
# output_folder: /media/nas_data/Thomas/S1/processed/MNI_2018_new_final
output_folder: /media/tweiss/Daten/try_preprocessing
# output_folder: /media/nas_data/Thomas/poland_processed
# output_folder: /media/nas_data/Thomas/foggia_italy_processed

# Location of SNAP's graph-processing-tool
gpt: /home/tweiss/snap/bin/gpt

# Location of xml files for processing (not needed if default version is used)
xml_graph_path: /media/tweiss/Work/GIT/GitHub/multiply-org/sar-pre-processing/sar_pre_processing/user_defined_graphs

# file names of xml graphs (not needed if default version is used)
pre_process_step1: test_pre_process_step1.xml
pre_process_step1_border: test_pre_process_step1_border.xml
pre_process_step2: test_pre_process_step2.xml
pre_process_step3: test_pre_process_step3.xml

subset: 'yes'

# # if subset = 'yes', region must be specified
# region:
#   ul:
#     lat: 47.8782
#     lon: 10.6168
#   lr:
#     lat: 47.8486
#     lon: 10.6699

region:
  ul:
    lat: 48.40
    lon: 11.60
  lr:
    lat: 48.10
    lon: 11.90


# foggia
# region:
#   ul:
#     lat: 41.44310092761187
#     lon: 15.396523233452278
#   lr:
#     lat: 41.299146707374895
#     lon: 15.5871227545953

# poland
# region:
#   ul:
#     lat: 53.51353092761188
#     lon: 22.526527143706467
#   lr:
#     lat: 53.36957669116146
#     lon: 22.766659589784574

speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '5'
  single_filter:
    apply: 'yes'

year: 2017

# normalisation_angle:

