
# Input folder with SAR data (zip format)
# input_folder: /media/nas_data/Thomas/S1/data/MNI
# input_folder: /media/tweiss/Daten/test_preprocessing/data
# input_folder: /media/nas_data/Thomas/Sentinel_1_data/biebrza_poland
# input_folder: /media/nas_data/Thomas/Sentinel_1_data/foggia_italy
# input_folder: /media/nas_data/Thomas/S1/data/Wallerfing
input_folder: /media/tweiss/Daten/try_preprocessing/data

# Folder to store the pre-processed data
# output_folder: /media/nas_data/Thomas/S1/processed/MNI_2017
output_folder: /media/tweiss/Daten/try_preprocessing
# output_folder: /media/nas_data/Thomas/poland_processed
# output_folder: /media/nas_data/Thomas/foggia_italy_processed

# Location of SNAP's graph-processing-tool
gpt: /home/tweiss/snap/bin/gpt
# gpt: /home/wodan/snap/bin/gpt

# Location of xml files which are needed for processing
xml_graph_path: /media/tweiss/Work/GIT/GitHub/multiply-org/sar-pre-processing/xml_files
# xml_graph_path: /media/wodan/data/Arbeit/GitHub/multiply-org/sar-pre-processing/xml_files


subset: 'yes'

# if subset = 'yes', region must be specified
# region:
#   ul:
#     lat: 47.8782
#     lon: 10.6168
#   lr:
#     lat: 47.8486
#     lon: 10.6699

region:
  ul:
    lat: 48.33
    lon: 11.65
  lr:
    lat: 48.23
    lon: 11.78


# foggia
# region:
#   ul:
#     lat: 41.44310092761187
#     lon: 15.396523233452278
#   lr:
#     lat: 41.299146707374895
#     lon: 15.5871227545953

# poland
# region:
#   ul:
#     lat: 53.51353092761188
#     lon: 22.526527143706467
#   lr:
#     lat: 53.36957669116146
#     lon: 22.766659589784574

speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: 5
  single_filter:
    apply: 'yes'

year: 2017

# normalisation_angle:

